# MSIX Conversion Accelerator

PackageName: MyAutomation

PublisherName: MyAutomation

PackageVersion: 1.0.1.0

EligibleForConversion: Yes

ConversionStatus: Package Created. Need Validation

Edition: Microsoft Windows 11 Pro

MinimumOSVersion: 24H2

MinimumOSBuild: 26100.6584

Architecture: 64

MSIXConversionToolVersion: 1.2024.405.0

AcceleratorVersion: 1.0.0

